# Generated by Django 6.0.3 on 2026-04-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_playlist_games_alter_playlist_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='in_playlist',
            field=models.BooleanField(default=False),
        ),
    ]
