# Generated by Django 6.0.3 on 2026-04-16 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_in_playlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='in_playlist',
        ),
        migrations.AddField(
            model_name='playlist',
            name='name',
            field=models.CharField(default='My Playlist', max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='preview_video',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='games.game'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
