# Generated by Django 6.0.3 on 2026-04-20 08:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_review_options_review_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='games/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
